use serde::{Deserialize, Serialize};
use std::env;
use std::fs::{self, File, create_dir_all};
use std::io::Write;
use std::path::PathBuf;
use std::sync::{LazyLock, RwLock};

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct General {
    pub margin: i32,
    pub spacing: i32,
}

impl Default for General {
    fn default() -> Self {
        General {
            margin: 5,
            spacing: 15,
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct Bar {
    pub height: i32,
    pub time_format: String,
}

impl Default for Bar {
    fn default() -> Self {
        Bar {
            height: 30,
            time_format: "%b %e %l:%M %p".to_string(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct Background {
    pub path: String,
}
impl Default for Background {
    fn default() -> Self {
        Background {
            path: "null".to_string(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct Config {
    pub general: General,
    pub bar: Bar,
    pub background: Background,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            general: General::default(),
            bar: Bar::default(),
            background: Background::default(),
        }
    }
}

static CONFIG: LazyLock<RwLock<Config>> = LazyLock::new(|| RwLock::new(Config::default()));

pub fn get_config() -> std::sync::RwLockReadGuard<'static, Config> {
    CONFIG.read().unwrap()
}

pub fn get_config_mut() -> std::sync::RwLockWriteGuard<'static, Config> {
    CONFIG.write().unwrap()
}

fn config_path() -> Option<PathBuf> {
    let home = env::var("HOME").ok()?;
    let mut path = PathBuf::from(home);
    path.push(".config/grr/config.toml");
    Some(path)
}

pub fn check_config_present(default_config: &Config) {
    let Some(config_path) = config_path() else {
        std::process::exit(1);
    };

    if let Some(parent_dir) = config_path.parent() {
        if let Err(e) = create_dir_all(parent_dir) {
            println!("Failed to create config directory: {e}");
            std::process::exit(1);
        }
    }

    if !config_path.is_file() {
        match toml::to_string(default_config) {
            Ok(toml_string) => match File::create(&config_path) {
                Ok(mut file) => {
                    if let Err(e) = file.write_all(toml_string.as_bytes()) {
                        println!("Failed to write config file content: {e}");
                        std::process::exit(1);
                    }
                }
                Err(e) => {
                    println!("Failed to create config file: {e}");
                    std::process::exit(1);
                }
            },
            Err(e) => {
                println!("Failed to serialize default config: {e}");
                std::process::exit(1);
            }
        }
    }
}

pub fn init_config() {
    check_config_present(&get_config());

    let Some(config_path) = config_path() else {
        std::process::exit(1);
    };

    let contents = match fs::read_to_string(&config_path) {
        Ok(s) => s,
        Err(e) => {
            println!("Failed to read config file: {e}");
            std::process::exit(1);
        }
    };

    match toml::from_str::<Config>(&contents) {
        Ok(parsed) => {
            let mut c = get_config_mut();
            *c = parsed;
        }
        Err(e) => {
            println!("Failed to parse config file, using defaults: {e}");
            std::process::exit(1);
        }
    }
}

pub fn save() {
    let config_path = match config_path() {
        Some(p) => p,
        None => {
            println!("Failed to determine config path: HOME not set");
            std::process::exit(1);
        }
    };

    if let Some(parent_dir) = config_path.parent() {
        if let Err(e) = create_dir_all(parent_dir) {
            println!("Failed to create config directory: {e}");
            std::process::exit(1);
        }
    }

    let disclaimer_string = concat!(
        "# Do not edit this file while the shell is running ( Your settings will be reset ) \n",
        "# Any comments / extra values added to this file will be removed on next save\n",
    );

    let toml_string = match toml::to_string(&*get_config()) {
        Ok(s) => s,
        Err(e) => {
            println!("Failed to serialize config: {e}");
            std::process::exit(1);
        }
    };

    let string = disclaimer_string.to_string() + &toml_string;

    match File::create(&config_path) {
        Ok(mut file) => {
            if let Err(e) = file.write_all(string.as_bytes()) {
                println!("Failed to write config file: {e}");
                std::process::exit(1);
            }
        }
        Err(e) => {
            println!("Failed to create config file: {e}");
            std::process::exit(1);
        }
    }
}
